### ISSUE TITLE
WGan's result in celeba training-data

### ISSUE THREAD

**Issue by zhangqianhui** [shekkizh/WassersteinGAN.tensorflow#8]

**Comment by zhangqianhui** [comment]
It looks that wgan generator  face images have low quality compared to the origin DCGAN.

**Comment by shekkizh** [comment]
Quality is certainly a relative term. My take from WGAN is that earlier training didn't have a quantifiable measure to understand the learning but with this modified formulation you get an idea of your model. This is actually better than training long hours and hoping your results turn out good or visualizing model every hour or so to check generated results.

Also, note that the results I posted in Readme are from randomly sampled points.

**Comment by zhangqianhui** [comment]
thanks
